# Generated by Django 5.2.4 on 2025-07-21 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiteratureBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isbn13", models.CharField(max_length=13, unique=True)),
                ("isbn10", models.CharField(blank=True, max_length=10, null=True)),
                ("title", models.CharField(max_length=500)),
                ("subtitle", models.CharField(blank=True, max_length=500)),
                ("authors", models.CharField(max_length=300)),
                ("categories", models.CharField(blank=True, max_length=200)),
                ("thumbnail", models.URLField(blank=True)),
                ("description", models.TextField()),
                ("published_year", models.IntegerField(blank=True, null=True)),
                (
                    "average_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("num_pages", models.IntegerField(blank=True, null=True)),
                ("ratings_count", models.IntegerField(blank=True, null=True)),
                (
                    "booktitle_alt",
                    models.CharField(
                        blank=True,
                        help_text="Alternative title from popularity dataset",
                        max_length=500,
                    ),
                ),
                (
                    "author_alt",
                    models.CharField(
                        blank=True,
                        help_text="Alternative author from popularity dataset",
                        max_length=300,
                    ),
                ),
                (
                    "popularity_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("votes_count", models.IntegerField(blank=True, null=True)),
                ("popularity_score", models.BigIntegerField(blank=True, null=True)),
                (
                    "themes",
                    models.TextField(blank=True, help_text="Comma-separated themes"),
                ),
                (
                    "reading_difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("moderate", "Moderate"),
                            ("challenging", "Challenging"),
                            ("difficult", "Difficult"),
                        ],
                        default="moderate",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("genres", models.ManyToManyField(blank=True, to="accounts.genre")),
            ],
            options={
                "ordering": ["-average_rating", "-published_year"],
            },
        ),
        migrations.CreateModel(
            name="TechBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                ("author", models.CharField(max_length=200)),
                ("isbn10", models.CharField(blank=True, max_length=10, null=True)),
                ("isbn13", models.CharField(blank=True, max_length=13, null=True)),
                ("publish_date", models.DateField(blank=True, null=True)),
                ("edition", models.CharField(blank=True, max_length=50)),
                ("best_seller", models.BooleanField(default=False)),
                ("top_rated", models.BooleanField(default=False)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("review_count", models.IntegerField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "tech_categories",
                    models.TextField(
                        blank=True, help_text="Comma-separated tech categories"
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "programming_languages",
                    models.ManyToManyField(
                        blank=True, to="accounts.programminglanguage"
                    ),
                ),
            ],
            options={
                "ordering": ["-rating", "-publish_date"],
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("tech", "Tech Agent"),
                            ("literature", "Literature Agent"),
                        ],
                        max_length=20,
                    ),
                ),
                ("book_title", models.CharField(max_length=500)),
                ("book_author", models.CharField(max_length=300)),
                ("book_isbn", models.CharField(blank=True, max_length=13)),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, help_text="Confidence score 0-1", max_digits=3
                    ),
                ),
                ("reason", models.TextField(help_text="Why this book was recommended")),
                (
                    "context_query",
                    models.TextField(
                        help_text="Original user query that led to this recommendation"
                    ),
                ),
                (
                    "user_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Poor"),
                            (2, "Fair"),
                            (3, "Good"),
                            (4, "Very Good"),
                            (5, "Excellent"),
                        ],
                        null=True,
                    ),
                ),
                ("user_feedback", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "literature_book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="books.literaturebook",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tech_book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="books.techbook",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="literaturebook",
            index=models.Index(fields=["title"], name="books_liter_title_a22219_idx"),
        ),
        migrations.AddIndex(
            model_name="literaturebook",
            index=models.Index(
                fields=["authors"], name="books_liter_authors_dde572_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="literaturebook",
            index=models.Index(
                fields=["average_rating"], name="books_liter_average_297048_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="literaturebook",
            index=models.Index(
                fields=["published_year"], name="books_liter_publish_2e24e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="techbook",
            index=models.Index(fields=["title"], name="books_techb_title_f59b27_idx"),
        ),
        migrations.AddIndex(
            model_name="techbook",
            index=models.Index(fields=["author"], name="books_techb_author_d35ea3_idx"),
        ),
        migrations.AddIndex(
            model_name="techbook",
            index=models.Index(fields=["rating"], name="books_techb_rating_e7c103_idx"),
        ),
        migrations.AddIndex(
            model_name="techbook",
            index=models.Index(
                fields=["best_seller"], name="books_techb_best_se_acf4c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["user", "agent_type"], name="books_recom_user_id_f8d062_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(fields=["score"], name="books_recom_score_a55f84_idx"),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["created_at"], name="books_recom_created_a89fc6_idx"
            ),
        ),
    ]
