# Generated by Django 4.2.7 on 2025-07-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Genre",
        ),
        migrations.DeleteModel(
            name="ProgrammingLanguage",
        ),
        migrations.AlterField(
            model_name="literaturebook",
            name="genres",
            field=models.ManyToManyField(blank=True, to="accounts.genre"),
        ),
        migrations.AlterField(
            model_name="techbook",
            name="programming_languages",
            field=models.ManyToManyField(blank=True, to="accounts.programminglanguage"),
        ),
    ]
