# Generated by Django 5.2.4 on 2025-07-21 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("tech", "Tech Agent"),
                            ("literature", "Literature Agent"),
                            ("manga", "Manga/Comics Agent"),
                            ("coordinator", "Agent Coordinateur"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "session_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Session identifier for tracking",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Conversation Histories",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[("user", "User"), ("agent", "Agent")], max_length=10
                    ),
                ),
                ("content", models.TextField()),
                (
                    "tokens_used",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of tokens used for this message",
                        null=True,
                    ),
                ),
                (
                    "processing_time",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Time taken to process message in seconds",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "rag_sources",
                    models.JSONField(
                        blank=True,
                        help_text="Sources used for RAG retrieval",
                        null=True,
                    ),
                ),
                (
                    "similarity_scores",
                    models.JSONField(
                        blank=True,
                        help_text="Similarity scores for retrieved documents",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.conversationhistory",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="conversationhistory",
            index=models.Index(
                fields=["user", "agent_type"], name="chat_conver_user_id_9fcfac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationhistory",
            index=models.Index(
                fields=["updated_at"], name="chat_conver_updated_1702c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="chat_messag_convers_3154fc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["sender"], name="chat_messag_sender_666dde_idx"),
        ),
    ]
