# Generated by Django 4.2.7 on 2025-07-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversationhistory",
            name="agent_type",
            field=models.CharField(
                choices=[
                    ("tech", "Tech Agent"),
                    ("literature", "Literature Agent"),
                    ("manga", "Manga Agent"),
                ],
                max_length=20,
            ),
        ),
    ]
